### ISSUE TITLE
WALA can used to static code slicing(SCS), right? 

### ISSUE THREAD

**Issue by yz-qiang** [wala/WALA#1060]
Hello, if WALA can be used to do it, how can I achieve this goal. And What is running environment is needed for WALA,. java 11, or java 8? 
Thank you :)

**Comment by yz-qiang** [comment]
For example, I have a **.java** file the code is: 
```
int i; 
int sum =0; 
int product =1; 
for(i =0; i < N;++i){ 
   sum = sum + i; 
   product = product *i; }
write(sum); 
write(product); 
```
I need to slice up the code that affects variable `sum`, the result as follows:
```
int i;
int sum=0; 
for (i=0; i<10; ++i){ 
     sum = sum+i;}
write(sum);
```
How do I get this code slice? If possible the input file type is **.java**. Please reply to me at your convenience, Thank you so much. I need your help :)

**Comment by msridhar** [comment]
See this documentation page:

https://github.com/wala/WALA/wiki/Slicer

In particular, note that WALA does _not_ produce executable slices.  Also note that simple copy statements may not appear in the slice:

https://github.com/wala/WALA/wiki/Slicer#warning-exclusion-of-copy-statements-from-slice

Since you want to slice `.java` files you want to use the WALA source frontend.  The `AstJavaSlicer` class is relevant:

https://github.com/wala/WALA/blob/master/com.ibm.wala.cast.java/src/main/java/com/ibm/wala/cast/java/ipa/slicer/AstJavaSlicer.java

The source frontend may preserve info about the copy statements, but I'm not sure.

Here is some test code using `AstJavaSlicer`:

https://github.com/wala/WALA/blob/2d6aa8affeb33db48716de8c5c15125d4f7719a5/com.ibm.wala.cast.java/src/testFixtures/java/com/ibm/wala/cast/java/test/JavaIRTests.java#L708-L768

Hope that helps!
