### ISSUE TITLE
How can I analyse the JDK source code?

### ISSUE THREAD

**Issue by DroseGao** [wala/WALA#1109]
I tried to use WALA on JDK8 source code, but I found that if I just copy the src.zip to my program, there will be nothing in the Entrypoints. the code is as follow:
```
 public static void main(String args[]) throws IOException, ClassHierarchyException, IllegalArgumentException,
            InvalidClassFileException, CancelException {
        File exFile = new FileProvider().getFile("Java60RegressionExclusions.txt");

        AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope("./out/production/wala/java/util/AbstractCollection.class", exFile);

        com.ibm.wala.ipa.cha.ClassHierarchy cha = ClassHierarchyFactory.make(scope); 
        Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
        System.out.println(entrypoints);
}
```
but what I got is just []

However, if I just take one of the java files out of the package and import again, it works. But in this way, I need to do a lot of works.

Thx!

**Comment by msridhar** [comment]
Sorry for the slow response.  I don't think treating JDK classes as "application" classes is supported in WALA, since there are various places where it is assumed that `java.lang` classes, etc are in the primordial scope.  What you could try to do instead is create your own version of `AllApplicationEntrypoints` that instead treats _every_ method (independent of classloader) as an entrypoint.  Hope that works, and let us know if you need more help.
