### ISSUE TITLE
Wala Class Hierarchy missing some classes

### ISSUE THREAD

**Issue by akshayutture** [wala/WALA#1151]
I was running WALA on the NJR benchmarks (https://zenodo.org/record/4632231#.YL_FGi9h2C) and a fraction of the benchmarks (25 out of 293) miss at least one class in the class-hierarchy. Inspecting the jar shows that the class is present, but Wala's class hierarchy seems to miss it.

### Example
Here is the link to one such benchmark (jar file):
https://drive.google.com/file/d/1ibA5gjcGy78_BjhA6u9le_kUCe8rGZ2e/view?usp=share_link
Missing class: `sg/edu/nus/cs5344/spring14/twitter/datastructure/Hashtag`

### Details
Wala version: 1.5.8
Jarfile complied with: Java 8
Classfile major number: 52
Classfile minor number: 0

### Code
```
import java.io.IOException;
import java.util.Properties;
import com.ibm.wala.classLoader.IClass;
import com.ibm.wala.core.util.config.AnalysisScopeReader;
import com.ibm.wala.ipa.callgraph.AnalysisScope;
import com.ibm.wala.ipa.cha.ClassHierarchy;
import com.ibm.wala.ipa.cha.ClassHierarchyException;
import com.ibm.wala.ipa.cha.ClassHierarchyFactory;
import com.ibm.wala.util.CancelException;
import com.ibm.wala.util.io.CommandLine;

public class Test2 {
	public static void main(String[] args) throws ClassHierarchyException, IOException, CancelException{
		Properties p = CommandLine.parse(args);
		String classpath = p.getProperty("jarfile");
		
		AnalysisScope scope = AnalysisScopeReader.instance.makeJavaBinaryAnalysisScope(classpath, null);
		ClassHierarchy cha = ClassHierarchyFactory.make(scope);
		for (IClass c : cha) {
			System.out.println(c.getName().toString());
		}
	}
}
```

**Comment by msridhar** [comment]
Thanks for the report!  The issue here is that the `Hashtag` class extends `org.apache.hadoop.io.Text`, which is not present in the test jar.  By default, WALA will not include a class in the class hierarchy if its superclass is missing.  If you want the class included anyway, I suggest using `ClassHierarchyFactory.makeWithRoot(scope)`, which will include the class, but treat its superclass as just being `java.lang.Object`.  I've added a bit of documentation on this here:

https://github.com/wala/WALA/wiki/Class-Hierarchy-Basics#missing-classes

Please let us know if this solves your issue.

**Comment by akshayutture** [comment]
Thank you so much for that prompt response and the documentation link. That was super helpful. This does resolve the issue.
