### ISSUE TITLE
Simplify Alfresco Maven repository configuration

### ISSUE THREAD

**Issue by liblit** [wala/WALA#1188]
@msridhar suggests that it may be possible to simplify or eliminate our configuration of an Alfresco Maven repository containing Eclipse JSDT packages:

> FWIW I think we stopped trying to build this project under Gradle since The Alfresco Maven repo was flaky; see #944.  Not sure if this changed recently.  If it hasn't, maybe there is some further cleanup possible?

_Originally posted by @msridhar in https://github.com/wala/WALA/pull/1184#discussion_r1059480850_

**Comment by liblit** [comment]
@msridhar is right that we stopped using Gradle to build `com.ibm.wala.ide.jsdt` and `com.ibm.wala.ide.jsdt.tests` in #944. However, I accidentally restored using Gradle to build these two components in #1174, when porting our build logic from Groovy to Kotlin. So far, building these two packages using Gradle has been working just fine. So perhaps we should keep it that way.

Recall that part of the justification for #944 was that "The modules are still built and tested via the 'Maven Eclipse tests' CI job", which is no longer the case. So if we don't build these components using Gradle either, then we're no longer building or testing them at all.

@msridhar, what are your thoughts on this matter?

**Comment by msridhar** [comment]
My concern is that the Alfresco repo will flake out again and break our builds.  We can leave things for now and wait and see if that happens.  If that does happen, I think our only option will be to stop building these projects entirely, at which point we might as well just delete the code from the master branch (possibly with a tag so that people can find it in the future).  But, we don't need to take immediate action.

**Comment by liblit** [comment]
That sounds like a sensible plan to me, @msridhar.
