### ISSUE TITLE
Why some submodules of WALA do not have .jar file on maven repo?

### ISSUE THREAD

**Issue by ljcppp** [wala/WALA#1205]
I'm a newbie to WALA tools. 
I wanna know why some submodules of WALA(like `com.ibm.wala.ide.jdt`) don't have related .jar on maven repository? I know some project use these module(like `https://github.com/funemy/SWORD`) and they have to clone them. I think that's not elegant. 
I sincerely hope someone can answer my doubts.

**Comment by msridhar** [comment]
@ljcppp the issue is that some modules have many Eclipse-related dependencies, and we haven't figured out a good way to bundle those modules for Maven Central such that the right deps get pulled in.  For your specific example, note that `com.ibm.wala.cast.java.ecj` _is_ on Maven Central and should provide similar functionality.  So, possibly the project you name could switch to using that?  If you know details on how we can do a better job with Maven packaging please share them.
