### ISSUE TITLE
Figure out how to update Eclipse version dependence

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#1354]
We currently depend on Eclipse 4.21.0 for the ECJ front end, which is quite old; the latest release is 4.30.0 (2023-12).  Older releases also have some kind of vulnerability (though I don't think this is a huge concern for us), fixed in 4.29.0:

https://gitlab.eclipse.org/security/cve-assignement/-/issues/8

The issue with just updating is that more recent Eclipse versions require JDK 17+ to run.  I don't think we want to force all of WALA to require JDK 17 to run.  But perhaps there is a way to only require JDK 17 if you want to run the ECJ front end.

**Comment by liblit** [comment]
> perhaps there is a way to only require JDK 17 if you want to run the ECJ front end.

This feels quite doable. We would need to use JDK 17 in just the Gradle submodules that call into JDK 17+ Eclipse code. All Eclipse-independent code can still use JDK 11.

To start, try adding the following to `build.gradle.kts` in each subdirectory that calls into ECJ:

```kotlin
java.toolchain.languageVersion = JavaLanguageVersion.of(17)
```

It's also possible that the right place for this configuration tweak is somewhere in `eclipse-maven-central.gradle.kts`, since that seems to be the place where the current version 4.21.0 is put to use. But I'd probably start by tweaking just one or two specific `*/build.gradle.kts` files, then retroactively deciding whether the `*/build.gradle.kts` files that needed to be changed are exactly the ones that use `eclipse-maven-central.gradle.kts`.

I cannot guarantee that this is all we need to do, but it's a good start.

**Comment by liblit** [comment]
I'm going to noodle around with this for a bit and see how far I get.
