### ISSUE TITLE
Configuration cache warning from markdownlint task

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#1467]
With the latest master branch I only get one configuration cache warning when running `./gradlew build`, which is great!

Here is the warning:

```
1 problem was found storing the configuration cache.
- Task `:markdownlint` of type `org.gradle.api.DefaultTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.11/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

I don't think this is a big deal, but @liblit FYI in case you think this is worth tracking down or reporting upstream.

**Comment by msridhar** [comment]
Nevermind @liblit already found this 🙂 https://github.com/appmattus/markdown-lint/issues/39

**Comment by liblit** [comment]
We're tracking [that bug report](https://github.com/appmattus/markdown-lint/issues/39) in our [Use Gradle configuration cache](https://github.com/orgs/wala/projects/1) project tracker. In fact, it's [the only item left not marked as "Done"](https://github.com/orgs/wala/projects/1/views/1?filterQuery=-status%3ADone).

We're also telling Gradle that [we know that the configuration cache is not supported for this task](https://github.com/wala/WALA/blob/e92583067c70a2d40884514f0db5e49a00cd4094/build.gradle.kts#L120), which is why you're seeing a warning instead of an error.
