### ISSUE TITLE
Allow WALA to support missing superclasses?

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#322]
Right now, when loading a class C into a `ClassHierarchy`, if a superclass of C cannot be resolved, then C is not added to the hierarchy:

https://github.com/wala/WALA/blob/bc0309b5ba9c8c59abdf3ee8fd94a83e1beec3c9/com.ibm.wala.core/src/com/ibm/wala/ipa/cha/ClassHierarchy.java#L310-L324

We have cases where we'd like a class to still be present in the hierarchy even if the superclass cannot be resolved.  Our client is just building IRs and CFGs and doing dataflow, but doesn't really rely on getting "correct" answers from the class hierarchy around subtyping, etc.  The problem is if a class is not present in the `ClassHierarchy` we can't even build an IR for it, as we won't be able to get the relevant `IMethod`s, etc.

The "right" fix for this would be to properly decouple resolution of names from type-hierarchy queries.  As a stopgap, I was thinking of hacking `ClassHierarchy` to soldier on when a supertype cannot be resolved, just making the (incorrect) assumption that the class extends the root type.  This would be guarded under an option that would be off by default.

@juliandolby any thoughts here?  I'm wondering if we are going to get burned somewhere that I've forgotten.

/cc @subarnob @lazaroclapp

**Comment by reddr** [comment]
Pushing this again as it's only partially usable, see discussion in #335 .
I see two possible solutions to the problem:
1. **makeWithRoot()**: Replace missing superclass with hierarchy root (requires almost no changes, side-effect: superclass info is missing)
2. **makeWithPhantom()**: Replace missing superclass with wala-synthetic PhantomSuperclass that holds the name of the missing superclass.

The proposed patches try to establish 2., however fail in the following condition:
https://github.com/wala/WALA/pull/335#issuecomment-427007521

**Comment by reddr** [comment]
@msridhar ok, I can put up a PR for 1. 

It would probably look like this:
- in the Factory, I would replace the boolean _makeWithPhantom_ arg by an enum { NORMAL, PHANTOM, ROOT }
- reintroduce the _NoSuperclassFoundException_ class and replicate the try-catch block to check for it 
- if _makeWithRoot_ was called the _superClass_ would then simply be set to the rootType

What do you think? Or is your goal to have this as a short-term solution that is not extended but _replaced_ by makeWithPhantom?  In this case, I would stick to the boolean arg instead of introducing an enum.

**Comment by msridhar** [comment]
@reddr your approach sounds fine.  I'd like to get phantom classes working eventually to give more info to analysis clients, but no timeline on that, and I'm happy to keep the ROOT approach around long-term.
