### ISSUE TITLE
how to publish to maven local using gradle?

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#326]
I tried `./gradlew publishToMavenLocal` and that stuck the source jars in `~/.m2/repository` but not the actual jar file with all the classes:

```
$ ./gradlew publishToMavenLocal
Parallel execution is an incubating feature.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
114 actionable tasks: 56 executed, 58 up-to-date
msridhar-C02S32J4G8WM:wala msridhar$ ls -al ~/.m2/repository/com/ibm/wala/com.ibm.wala.core/1.5.0-SNAPSHOT/
total 2072
drwxr-xr-x  5 msridhar  staff      160 Jul 12 10:51 .
drwxr-xr-x  4 msridhar  staff      128 Jul 12 10:51 ..
-rw-r--r--  1 msridhar  staff  1050596 Jul 12 10:51 com.ibm.wala.core-1.5.0-SNAPSHOT-sources.jar
-rw-r--r--  1 msridhar  staff      486 Jul 12 10:51 com.ibm.wala.core-1.5.0-SNAPSHOT.pom
-rw-r--r--  1 msridhar  staff      756 Jul 12 10:51 maven-metadata-local.xml
```

When I do `mvn clean install -DskipTests` all relevant jars are installed:
```
$ ls -al ~/.m2/repository/com/ibm/wala/com.ibm.wala.core/1.5.0-SNAPSHOT/
total 5552
drwxr-xr-x  9 msridhar  staff      288 Jul 12 10:52 .
drwxr-xr-x  4 msridhar  staff      128 Jul 12 10:51 ..
-rw-r--r--  1 msridhar  staff      366 Jul 12 10:52 _remote.repositories
-rw-r--r--  1 msridhar  staff     1087 Jul 12 10:52 com.ibm.wala.core-1.5.0-SNAPSHOT-p2artifacts.xml
-rw-r--r--  1 msridhar  staff    10238 Jul 12 10:52 com.ibm.wala.core-1.5.0-SNAPSHOT-p2metadata.xml
-rw-r--r--  1 msridhar  staff  1051128 Jul 12 10:52 com.ibm.wala.core-1.5.0-SNAPSHOT-sources.jar
-rw-r--r--  1 msridhar  staff  1696324 Jul 12 10:52 com.ibm.wala.core-1.5.0-SNAPSHOT.jar
-rw-r--r--  1 msridhar  staff      528 Jun 29 14:13 com.ibm.wala.core-1.5.0-SNAPSHOT.pom
```

`com.ibm.wala.core-1.5.0-SNAPSHOT.jar` is the key file.  I'd much rather do this with Gradle than Maven 😄 @liblit any thoughts?

**Comment by liblit** [comment]
The `publishToMavenLocal` task is available due to 1d8869bb0a5966085755c6be5e98a69a051a744f, which represented my first, tentative foray into Gradle-driven publishing of build artifacts. As noted in that commit’s description, though, the published artifacts include only source archives. I never continued beyond that to include bytecode.

Prompted by @msridhar’s question, I am now looking into expanding the published artifacts to include bytecode. This surely will require a few rounds of iteration to get right. With help from @msridhar and any other Maven-interested parties, I am confident that we can get something working eventually.

More news when I have it!

**Comment by liblit** [comment]
My personal WALA repository clone now has [an experimental `more-complete-publishing` branch](https://github.com/liblit/WALA/tree/more-complete-publishing) that includes all of WALA’s built Java bytecode jar archives in `publishToMavenLocal`. There are definitely some differences between the artifacts published by Maven and Gradle, especially in `*.pom` files and in jar-embedded `META-INF/MANIFEST.MF` files. However, I do not know which of those differences matter and which are incidental or reflect Maven historical baggage.

@msridhar, perhaps you could test this out? You could clone [my experimental `more-complete-publishing` branch](https://github.com/liblit/WALA/tree/more-complete-publishing) branch and run `./gradlew publishToMavenLocal` into an otherwise clean `~/.m2/repository`. Then try to use the Gradle-populated `~/.m2/repository` in whatever other WALA-based project you are working on. Does it work? If it fails, can we determine what Gradle/Maven difference causes the failure?

**Comment by msridhar** [comment]
@liblit sorry for the slow response.  I cloned your branch, and using the Maven local version of WALA from another project worked fine!  Can you open a PR with your change?
