### ISSUE TITLE
More descriptive messages when Gradle script fails

### ISSUE THREAD

**Issue by karimhamdanali** [wala/WALA#328]
Running the gradle script on a machine that doesn't have gcc/g++ causes the following error to be thrown:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/karim/workspace/swift-source/WALA/com.ibm.wala.cast.test/build.gradle' line: 40

* What went wrong:
A problem occurred configuring project ':com.ibm.wala.cast.test'.
> Exception thrown while executing model rule: tasks { ... } @ com.ibm.wala.cast.test/build.gradle line 88, column 2
   > Exception thrown while executing model rule: checkSmoke_main(org.gradle.api.tasks.Exec) { ... } @ com.ibm.wala.cast.test/build.gradle line 97, column 3
      > Cannot get property 'linkFiles' on null object
```

Despite being detailed, the error does not actually point out to the original root cause as to why the script fails (i.e., missing gcc/g++). Perhaps, the script can check the existence of g++/gcc prior to execution and print a more actionable error message to the user. Alternatively, is it possible to intercept that error message and augment it with some explanation about its root cause?

- Karim

**Comment by karimhamdanali** [comment]
@liblit I believe you are probably the best person to tag in this thread :)

**Comment by liblit** [comment]
I will look into this shortly; we should be able to do better. But at the risk of seeming judgmental…what kind of philistine uses a machine without gcc/g++ installed? :stuck_out_tongue:

**Comment by liblit** [comment]
Gradle already has perfectly good explanatory diagnostics in the case where no C/C++ compiler toolchain is available. Unfortunately, we were dereferencing `null` before Gradle could get far enough to show those messages. Once #333 is merged, you will see the standard Gradle explanation, which should look something like the following:

```
* What went wrong:
Execution failed for task ':com.ibm.wala.cast:compileCastSharedLibraryCastCpp'.
> No tool chain is available to build for platform 'linux_x86-64':
    - Tool chain 'visualCpp' (Visual Studio): Visual Studio is not available on this operating system.
    - Tool chain 'gcc' (GNU GCC): Could not find C compiler 'gcc' in system path.
    - Tool chain 'clang' (Clang): Could not find C compiler 'clang' in system path.
```

Furthermore, this should only trigger if you ask Gradle to do something that requires native compilation. For example, `./gradlew assemble` will work fine, as will `./gradlew publishToMavenLocal`. However, `./gradlew build` will eventually fail with the above message, since `build` runs all tests, and some tests require native compilation.

**Comment by karimhamdanali** [comment]
In my defense, it's a new server that I just got for my group, and I completely forgot about that! So I certainly assumed it has g++/gcc when I was compiling this. Thanks Ben and Manu for taking care of this one.
