### ISSUE TITLE
Problem installing WALA and compiling tests

### ISSUE THREAD

**Issue by bronevet** [wala/WALA#384]
I just grabbed a copy of WALA via "git clone https://github.com/wala/WALA.git" and built it using " ./gradlew build".
25 tests pass, 1 test failed:
com.ibm.wala.cast.test.TestNativeTranslator > testNativeCAst FAILED
    java.lang.UnsatisfiedLinkError at TestNativeTranslator.java:33

I then tried to compile one of the tests via:
javac -cp "/usr/local/buildtools/java/jdk/jre/lib/rt.jar" com.ibm.wala.ide.jdt.test/source/com/ibm/wala/cast/java/test/JDTJavaIRTests.java 

javac couldn't find any of the imports (e.g. import com.ibm.wala.cast.java.jdt.test.Activator;) and I can't figure out how to point it at the right jar files. I see hundreds of jar files in the WALA directory but when I try to add the likely-looking ones to the javac -cp argument, it has no effect: 

javac -cp "/usr/local/buildtools/java/jdk/jre/lib/rt.jar;./com.ibm.wala.cast.java.test/build/libs/com.ibm.wala.cast.java.test-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.js.test.data/build/libs/com.ibm.wala.cast.js.test.data-1.5.1-SNAPSHOT.jar;./com.ibm.wala.ide.jdt.test/build/libs/com.ibm.wala.ide.jdt.test-1.5.1-SNAPSHOT.jar;./gradle/wrapper/gradle-wrapper.jar;./com.ibm.wala.cast.js.rhino/build/libs/com.ibm.wala.cast.js.rhino-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.js.nodejs.test/build/libs/com.ibm.wala.cast.js.nodejs.test-1.5.1-SNAPSHOT.jar;./com.ibm.wala.dalvik/build/libs/com.ibm.wala.dalvik-1.5.1-SNAPSHOT.jar;./com.ibm.wala.core/build/libs/com.ibm.wala.core-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.test/build/libs/com.ibm.wala.cast.test-1.5.1-SNAPSHOT-test.jar;./com.ibm.wala.cast.test/build/libs/com.ibm.wala.cast.test-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.js.rhino.test/build/libs/com.ibm.wala.cast.js.rhino.test-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.js.rhino.test/build/libs/com.ibm.wala.cast.js.rhino.test-1.5.1-SNAPSHOT-test.jar;./com.ibm.wala.util/build/libs/com.ibm.wala.util-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.java/build/libs/com.ibm.wala.cast.java-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.java.test.data/build/libs/com.ibm.wala.cast.java.test.data-1.5.1-SNAPSHOT.jar;./com.ibm.wala.ide.jsdt/build/libs/com.ibm.wala.ide.jsdt-1.5.1-SNAPSHOT.jar;./com.ibm.wala.cast.js.test/build/libs/com.ibm.wala.cast.js.test-1.5.1-SNAPSHOT-test.jar;./com.ibm.wala.cast.js.test/build/libs/com.ibm.wala.cast.js.test-1.5.1-SNAPSHOT.jar;./com.ibm.wala.ide.jsdt.tests/build/libs/com.ibm.wala.ide.jsdt.tests-1.5.1-SNAPSHOT.jar;./buildSrc/build/libs/buildSrc.jar" com.ibm.wala.ide.jdt.test/source/com/ibm/wala/cast/java/test/JDTJavaIRTests.java 

Any ideas about what I might be doing wrong? Thanks!

**Comment by liblit** [comment]
We have at least two unrelated issues here.

----

First, the test failure:

> ```
> 25 tests pass, 1 test failed:
> com.ibm.wala.cast.test.TestNativeTranslator > testNativeCAst FAILED
> java.lang.UnsatisfiedLinkError at TestNativeTranslator.java:33
> ```

This test involves a shared library that uses JNI to implement one or more `native` methods. Failing with an `UnsatisfiedLinkError` suggests that the shared library could not be loaded, or was loaded but did not implement the required `native` method(s). The logic for building and running this specific test is quite platform-dependent. What platform are you running this failing test on? What specific Linux distribution and version or macOS version are you using?

You might also try running `./gradlew test --tests=TestNativeTranslator.testNativeCAst --info`. The `test --tests=TestNativeTranslator.testNativeCAst` part of that command instructs Gradle to run only the specific test that was failing for you. The `--info` flag produces more verbose output reporting what Gradle is doing. Look through that output and see if you find any clues as to where things are going wrong trying to find and load the shared library.

Disclaimer: my own WALA build environment is currently broken for unrelated reasons. Unfortunately that prevents me from fully checking the recommendations I am giving you. I _think_ the preceding command will do what I described, but have not been able to verify this myself.

----

Next, the `JDTJavaIRTests.java` compilation failure:

In general, Gradle should already be compiling test files on its own as part of the `build` target. However, [the specific file that you selected is currently excluded from Gradle tests](https://github.com/wala/WALA/blob/dfa22d17a1d94de73b679de30a8e4b1b69328a1e/com.ibm.wala.ide.jdt.test/build.gradle#L36). I am not sure what exactly was causing us problems with this test under Gradle, but its exclusion suggests that trying to compile it yourself may be a poor choice.

Gradle does not make it easy to simply dump out the class path that it would use for a given target. If possible, this is something you should avoid caring about anyway. Instead, you should prefer one of these two options:

1. If you can chose your build system, then build your own WALA-based project using Gradle too. Set up your project as a [composite build](https://docs.gradle.org/current/userguide/composite_builds.html) with WALA as an included build within that composite build. I use this extensively and it works very well.

1. If you do not have the option of using Gradle for your own project, then use `./gradlew publishToMavenLocal` to build WALA and export its JAR files to a local Maven repository. Then build your project with that local Maven repository as a source of dependencies, by whatever means your build system has to manage that. This works well if, for example, you must use Maven instead of Gradle for your own project.

If you really must know Gradle's class path for some target, [something along these lines](https://stackoverflow.com/a/26825979/91929) might work for you. As noted above, I have not been able to test this out myself due to unrelated technical difficulties with my own WALA build environment.

**Comment by liblit** [comment]
@bronevet , it's been over a year since we heard from you on these problems. I am going to assume that the problem no longer occurs or is no longer relevant. If you're still having these same problems, please reopen this ticket or file new tickets.
