### ISSUE TITLE
Proposal: Google Java Format all the things

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#409]
I've found some recent code reviews to be hard to read due to inconsistent source code formatting in the repo.  I propose we use [Google Java Format](https://github.com/google/google-java-format) (GJF) to get rid of this problem for Java code.  The basic idea would be:

* Leverage the [GJF Gradle plugin](https://github.com/sherter/google-java-format-gradle-plugin) to run GJF and verify that code is formatted.
* Modify `gradlew` to install a Git pre-commit hook that formats code at commit time.  Once this is run once, auto-formatting should be automatic for developers.
* On CI, run `./gradlew verGJF` to ensure code is formatted correctly.
* Initially have one massive commit that reformats the whole repo.  (Anyone with outstanding changes will have to do a slightly tricky rebase, so this would have to be announced / coordinated properly.)

This is the setup we use with NullAway.  There are other setups like [pre-commit](https://pre-commit.com) that don't require hacking `gradlew` to install a pre-commit hook, but they require installation of a separate tool.

@liblit @juliandolby thoughts?  If we're on the same page I can put this together.

**Comment by liblit** [comment]
Overall: :+1:.

I have only weak opinions about code formats, but a _strong_ opinion that whatever format is used must have good tool integration. GJF is available as a command-line tool, a Gradle plugin, an IntelliJ IDEA plugin, an Eclipse plugin, and more. That makes it a fine choice in my book.

> Modify `gradlew` to install a Git pre-commit hook that formats code at commit time. Once this is run once, auto-formatting should be automatic for developers.

I would expect that any modifications to `gradlew` will be overwritten the next time we upgrade Gradle. Remembering to restore our tweaks seems like a hassle. @msridhar, apparently you have found this to be reasonable in practice on other projects?

Why not install Git hooks under Gradle control as a task that can be run explicitly, or run implicitly as a dependency of other tasks? [This gist](https://gist.github.com/KenVanHoeylandt/c7a928426bce83ffab400ab1fd99054a) shows a nice way to do it by creating a Gradle task to do the work and having the standard `build` task depend on it. [This Gradle plugin](https://github.com/STAR-ZERO/gradle-githook) also looks helpful.

> On CI, run `./gradlew verGJF` to ensure code is formatted correctly.

Agreed. It would also be easy to hook that up so that it runs as part of `./gradlew build` along with all of our other tests. Literally just a one-line change to add `build.dependsOn verGJF` to the top-level `build.gradle`.

> Initially have one massive commit that reformats the whole repo. (Anyone with outstanding changes will have to do a slightly tricky rebase, so this would have to be announced / coordinated properly.)

I often have a backlog of pending code-janitor cleanups. As @msridhar has probably noticed by now, I typically space these out to have no more than one or two as pull requests awaiting review at any one time. I would like to drain my current queue before a mass reformatting. Right now I have #408 waiting for review from @juliandolby, and then three more cleanup batches waiting in line:

1. Improved JarFileModule entry iteration.
1. Fix 248 uses of raw types, leaving just 25 unfixed.
1. Updates to IDE diagnostics configurations.

I'd like to drain the first two before any mass-reformatting, _especially_ the second since it touches so much code. The third can happen either before or after, as it does not touch any Java code.

**Comment by liblit** [comment]
> I think probably better to just add the `verGJF` task onto the CI gradle command (like [here](https://github.com/uber/NullAway/blob/master/.travis.yml#L18)). If we make `build` depend on `verGJF` then you won't even be able to build locally until you've run the formatter.

Confusingly, `build` is the Gradle lifecycle task that builds everything _and_ runs all tests. You would use `./gradlew assemble` to build everything without also running tests.

If checking formatting should be part of the automated test suite, then triggering that check as a dependency of `./gradlew build` is the right approach.

**Comment by liblit** [comment]
> No hurry on this, I can certainly wait until your outstanding changes are landed.

Thanks, I appreciate that. For my part, I will postpone any further janitorial work until we either land the mass reformatting or decide not to. No sense adding to a queue that we may need to drain.

**Comment by msridhar** [comment]
> If checking formatting should be part of the automated test suite, then triggering that check as a dependency of `./gradlew build` is the right approach.

I think we should only be checking formatting for code right before it is merged to master, not as part of the automated tests.  So tweaking things in the CI scripts seems like the right approach.

**Comment by liblit** [comment]
> I think we should only be checking formatting for code right before it is merged to master, not as part of the automated tests. So tweaking things in the CI scripts seems like the right approach.

OK with me.
