### ISSUE TITLE
Cannot resolve expression ${workspace_loc:/com.ibm.wala}

### ISSUE THREAD

**Issue by karimhamdanali** [wala/WALA#438]
I've followed the build steps @ https://github.com/wala/WALA/blob/master/README-Gradle.md#eclipse to build WALA and import it into Eclipse as a Gradel project. However, when I try running the script `After Importing WALA Into Eclipse`, I get the following error:

` Cannot resolve expression ${workspace_loc:/com.ibm.wala}.`

Where should the directory `com.ibm.wala` be? I have `WALA` in the main workspace directory, but not `com.ibm.wala`.

Thanks.
- Karim

**Comment by msridhar** [comment]
@liblit any ideas here?

**Comment by liblit** [comment]
`${workspace_loc:/com.ibm.wala}` should expand to the path to the top-level `com.ibm.wala` project, which ought to have been created when you imported WALA into Eclipse. Do you have a top-level `com.ibm.wala` project? If not, then by what name is the overall WALA project known in your Eclipse workspace?

**Comment by karimhamdanali** [comment]
The overall WALA project is under the name `WALA` when I clone the repo and/or when I import it into Eclipse.

**Comment by liblit** [comment]
I just imported a pristine WALA clone into Eclipse using the “Existing Gradle Project” import wizard. The WALA tree is in a `WALA` subdirectory in my file system, but that did not matter: Eclipse named the top-level imported project “com.ibm.wala”, not “WALA”. Running the “After Importing WALA Into Eclipse” launcher worked just fine. The `${workspace_loc:/com.ibm.wala}` variable used in that launcher’s configuration correctly expanded to the absolute file system path of the Eclipse project identified by the workspace path `/com.ibm.wala`. Note that `/com.ibm.wala` here refers to the top-level Eclipse project named `com.ibm.wala`: it is an Eclipse-internal path to a workspace resource, not a path in the file system. So all of this worked as designed and as expected.

@karimhamdanali, I cannot explain why Eclipse is naming your top-level imported project “WALA” instead of “com.ibm.wala”. I cannot reproduce that on my box. What version of Eclipse are you using? (That is a long shot, but I may as well ask.)

As a workaround, you could bring up the Run Configurations dialog for “After Importing WALA Into Eclipse”. You should see that the Working Directory is set to `${workspace_loc:/com.ibm.wala}`. Change that to `${workspace_loc:/WALA}` and it should run correctly, assuming that `WALA` really is what Eclipse named your top-level imported project. Unfortunately I cannot explain why Eclipse would do that for you and not for me.

**Comment by karimhamdanali** [comment]
Hi Ben,

I followed your instructions with a vanilla clone of WALA. However, I still get the same error. 

The filesystem directory name is `WALA`, the internal Eclipse name for the project is also `WALA` while the top-level project name is `com.ibm.wala` if I view it in the Gradle Tasks view.

I tried renaming the configuration to `${workspace_loc:/WALA}` but that also gives the same error. The only path that does work for me is `${workspace_loc}/WALA`, which expands to the absolute path on the machine.

I'm running Eclipse Version: 2019-03 M1 (4.11.0 M1), Build id: 20190117-2133 on a MacBook Pro running macOS Mojave 10.14.3.

**Comment by liblit** [comment]
@karimhamdanali wrote:
> The filesystem directory name is WALA, the internal Eclipse name for the project is also WALA while the top-level project name is com.ibm.wala if I view it in the Gradle Tasks view.
> 
> I tried renaming the configuration to ${workspace_loc:/WALA} but that also gives the same error.

Nutty. If neither `${workspace_loc:/WALA}` nor `${workspace_loc:/com.ibm.wala}` worked for you, then I am quite confused as to how Eclipse thinks you should be using these `$variables` to refer to the project.

> I'm running Eclipse Version: 2019-03 M1 (4.11.0 M1), Build id: 20190117-2133 on a MacBook Pro running macOS Mojave 10.14.3.

I upgraded my Eclipse installation to 2019-03 (4.11.0), Build id: 20190314-1200. My Buildship plugin (which provides Eclipse + Gradle integration) is at 3.0.1.v20181217-1554. My WALA tree is in a subdirectory named `WALA`, just like you. And for me, `${workspace_loc:/com.ibm.wala}` is definitely the right value.

The only relevant difference I can think of but cannot explore is that I'm running on Fedora Linux and you're using macOS. Maybe that matters. I do not have a macOS box to try this on, but @msridhar might.

OK, here's something you can try, @karimhamdanali:

1. Select Run → Run Configurations…
1. In the list on the left side of the Run Configurations dialog, select “After Importing WALA Into Eclipse”.
1. Erase any text currently in the “Working Directory” field.
1. Just below that field, click “Workspace…”
1. In the “Select Project” dialog, click whichever project seems to correspond to the top-level WALA project. For me, that’s “com.ibm.wala”.
1. In the “Select Project” dialog, click “OK”.

Back in the Run Configurations dialog, what text now appears in the “Working Directory” field? For me, that field is now set to “${workspace_loc:/com.ibm.wala}”, and that works as intended. What text appears there for you, and if you use that to run the configuration, does it launch correctly?

**Comment by karimhamdanali** [comment]
Following the steps, I still get the same error. The project name in Step 5 is "WALA". The string in "Working Directory" is `${workspace_loc:/WALA}`. I'm attaching a picture below.

![Screen Shot 2019-03-29 at 3 36 44 PM](https://user-images.githubusercontent.com/291001/55264108-ea0ede80-5238-11e9-9a01-8d4de35afeee.png)

**Comment by liblit** [comment]
There are at least two strange things happening, neither of which I can reproduce: (1) the imported project receiving an Eclipse project name other than `com.ibm.wala`, and (2) the `${workspace_loc}` variable not working when given an argument.

I remain unable to reproduce the first problem. Perhaps it is a macOS thing; as noted, I have no macOS machine on which to try this.

As for the second problem, if setting the working directory using only point-and-click mouse actions does not work, then that feels like an Eclipse bug. I recommend reporting this to Eclipse and/or looking for similar existing reports.

**Comment by karimhamdanali** [comment]
Ok. So latest effort shows that the error has 2 aspects to it:

1) I cannot have WALA be in the root directory of my workspace. It has to be in a subdirectory in the root directory of my workspace.

2) I had to use the working directory as `${workspace_loc}/WALA` (using the name of the WALA subdirectory on the filesystem).

With those 2 fixes, I was able to resolve the error and use the Gradle scripts as expected.

**Comment by liblit** [comment]
My best guess is that there are Eclipse bugs regarding `workspace_loc` expansion. As noted above:
> if setting the working directory using only point-and-click mouse actions does not work, then that feels like an Eclipse bug. I recommend reporting this to Eclipse and/or looking for similar existing reports.
