### ISSUE TITLE
Cache p2AsMaven deps on Travis?

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#446]
I am wondering if it would be possible to cache the p2AsMaven downloads / steps performed by the Gradle build on Travis.  These seem to not be cached and take quite a long time on each Travis job.  @liblit would this be possible, or is it dangerous?

**Comment by liblit** [comment]
## Is caching p2AsMaven useful?

I’ve looked at the time taken by the `p2AsMaven` stage in 17 recent Travis CI jobs:

Statistic|_M_:_SS_
-|-
minimum|2:46
median|4:04
mean|4:15
maximum|6:15

However, this may be a _very_ optimistic upper bound on the potential time savings. Even if we cache the `p2AsMaven` downloads, the cached copies themselves still need to be copied across a network to get from the Travis CI cache back onto the virtual build machine. This is why the Travis CI caching documentation [notes](https://docs.travis-ci.com/user/caching/#things-not-to-cache) that “Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source”. Later, the same documentation [further explains](https://docs.travis-ci.com/user/caching/#how-does-caching-work):

> Note that this [implementation strategy] makes our cache not network-local, it is still bound to network bandwidth and DNS resolutions. That impacts what you can and should store in the cache. If you store archives larger than a few hundred megabytes in the cache, it is unlikely that you’ll see a big speed improvement.

The material we would need to cache weighs in at 461 megabytes, making the benefits of caching unclear.

## Is caching p2AsMaven possible?

I believe so. It should suffice to add `"$TRAVIS_BUILD_DIR/build/p2asmaven"` to the `cache` → `directories` list in `.travis.yml`. I have not tested this myself, but that’s where `p2AsMaven` puts all of its downloads. If those downloads were preserved from one build and restored before another, I think that `p2AsMaven` should be unable to tell the difference.

## Is caching p2AsMaven dangerous?

I can think of one risk. Suppose the `p2AsMaven` download process breaks, perhaps due to removal or relocation of required files on the remote server. Caching the downloads across Travis CI runs might allow a Travis CI test to pass (using cached downloads) when it really should have failed (if it had attempted a fresh download). That, in turn, could delay discovery of the regression.

However, that this is a risk for _anything_ we might cache, not just `p2AsMaven`. For example, we are already caching `"$TRAVIS_BUILD_DIR/com.ibm.wala.core.testdata/ocaml/ocamljava-2.0-alpha1/lib"`, and have been doing so for quite some time: 3864bf20acd726ce51c3fbce3e8ae4e372c1da97. A change in the download URL for that material might not be discovered by Travis CI testing, but this does not appear to have been a problem in practice.

(Interestingly, the cached OCaml-Java download only helps the Maven build, as the Gradle build stores this download in a different location. So in fact, Travis CI _would_ catch this, but only because the Gradle build would not benefit from the cache anyway.)

## My recommendation?

Try it and see what kind of speedups we get, if any. Then weigh the size of those speedups against the risk of delayed regression detection. I think that the latter risk is quite small, so even a moderate performance boost may make this worth doing. But it is also possible that Travis CI’s network-traversing cache may mean there’s no measurable performance boost at all.

**Comment by msridhar** [comment]
Ok I'll give it a try.  My gut tells me the speedup will be significant; I feel like even on my local machine the p2AsMaven download doesn't come close to saturating my bandwidth.

**Comment by msridhar** [comment]
Here's a job with the new caching (this is the second run since the first initializes the cache).

https://travis-ci.org/msridhar/WALA/jobs/521526835

On the plus side, the cache download is really fast.  The build cache setup time is around 15s, which is way faster than the p2AsMaven stage.  On the down side, the change makes uploading an updated cache take longer.  However, in this case it seems the cache was updated for silly reasons:

```
0.00s62.70schange detected (content changed, file is created, or file is deleted):
/home/travis/.gradle/caches/5.2.1/fileHashes/fileHashes.bin
/home/travis/.gradle/caches/5.2.1/fileHashes/fileHashes.lock
/home/travis/.gradle/caches/5.2.1/fileHashes/resourceHashesCache.bin
/home/travis/.gradle/caches/5.2.1/javaCompile/javaCompile.lock
/home/travis/.gradle/caches/jars-3/0927e98c2523b864fd1951e97f89fca2/buildSrc.jar
/home/travis/.gradle/caches/journal-1/file-access.bin
/home/travis/.gradle/caches/journal-1/journal-1.lock
/home/travis/.gradle/caches/modules-2/metadata-2.69/module-metadata.bin
/home/travis/.gradle/caches/modules-2/metadata-2.69/module-versions.bin
```

I don't see why these files should be getting cached.  Maybe we can update our logic to delete more stuff before running the cache logic, so we can skip this step more often.  If we can get rid of unnecessary cache uploads I think this will be a clear win.

**Comment by liblit** [comment]
Sweet.
