### ISSUE TITLE
Why GraphPrint.genericToString() convert Graph to SlowSparseNumberedGraph?

### ISSUE THREAD

**Issue by coder-chenzhi** [wala/WALA#517]
I wonder why `GraphPrint.genericToString()` convert `Graph` to `SlowSparseNumberedGraph` before calling `toString()`? For comparison, Dotify just iterate the nodes and edges of `Graph` directly without the conversion. What's the benefit brought by the conversion?

**Comment by msridhar** [comment]
Can you link the code?

**Comment by msridhar** [comment]
Here's the code:

https://github.com/wala/WALA/blob/f0e2f04b6838849809cf596dabaa1d724a5c531b/com.ibm.wala.util/src/com/ibm/wala/util/graph/GraphPrint.java#L19-L33

My guess is this was just done because the behavior of `SlowSparseNumberedGraph.toString()` was well-known (whereas an arbitrary `Graph` might do something different).  Is this causing a problem?

**Comment by coder-chenzhi** [comment]
Thanks for your reply! @msridhar The code works fine. I am working on to serializing `SDG` in some well-known graph file format, like GraphML. So I want to figure out the best practice to iterate Graph, but I find two existing methods to print Graph in WALA. So I wonder which one is better, especially for the performance?

**Comment by msridhar** [comment]
Your best bet is just to iterate over the graph yourself and do the string
serialization I think. The use of SlowSparseNumberedGraph here is just for
convenience.

**Comment by msridhar** [comment]
Going to close this out, let me know if there's a follow-up question
