### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by michaelheilmann** [wala/WALA#54]
There are lots of warnings about redundant casts, redundant checks, .... in Eclipse. I will fix many of them soon and make the code using generics where possible (many old parts are written in pre-generics style). I announce that here, so there is no need for others to do that.

Is there a reason that `com.ibm.wala.util.collections.Filter` is deprecated?
The deprecation causes warnings all over the place.

**Comment by liblit** [comment]
Eclipse Oxygen currently (as of 65672f98ba0899ac1de88fc969059e90e4e75215) produces 23 warnings, down from roughly 5,000 back in aeac2a6df02b3b02c28fa3d20b36831efa405edc, just before I first started offering warning-fixing pull requests. Of the 23 warnings that remain:

- 3 are Plug-in Development problems addressed by pull request #227, currently waiting for attention from @juliandolby
- 8 are Plug-in Development problems addressed by pull request #246, currently waiting for attention from any WALA maintainer
- 10 are Potential Programming Problems that issue #236 asks some knowledgeable person to fix
- 2 are Type Safety and Raw Types problems that issue #244 asks some knowledgeable person to fix

I recommend that this broad “Fix warnings” issue be closed, since we already have either pending pull requests or more-narrowly-focused issues covering all warnings that remain.

**Comment by msridhar** [comment]
Agreed @liblit, closing
