### ISSUE TITLE
Exception: com.ibm.wala.ipa.callgraph.impl.FakeRootMethod cannot be cast to com.ibm.wala.classLoader.ShrikeBTMethod

### ISSUE THREAD

**Issue by zhangxii** [wala/WALA#541]
Hello, I am a new user of WALA.I've been slicing programs with WALA recently, and when I slice backward to the return statement of the example, I only get the return line. It also tells me that the `FakeRootMethod` type cannot be converted `ShrikeBTMethod` type.
What does this exception mean? And why my slice results are only one line?

My example is:
![image](https://user-images.githubusercontent.com/39162319/63650359-8e5f6780-c77c-11e9-8ea0-ba7abee7de87.png)

Here is my console output:
```
-------computeBackwardSlice-------
NORMAL_RET_CALLER:Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere[14]11 = invokevirtual < Application, Ljava/net/URLConnection, getContentType()Ljava/lang/String; > 7 @24 exception:10
NORMAL getContentType:return 11 Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
METHOD_ENTRY:Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
NORMAL fakeRootMethod:54 = new <Application,Ljava/lang/String>@48 Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere
Source line number = 25
NORMAL fakeRootMethod:56 = invokestatic < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > 54 @50 exception:57 Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere
METHOD_ENTRY:Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere
it's probably not a BT method (e.g. it's a fakeroot method)
com.ibm.wala.ipa.callgraph.impl.FakeRootMethod cannot be cast to com.ibm.wala.classLoader.ShrikeBTMethod
it's probably not a BT method (e.g. it's a fakeroot method)
com.ibm.wala.ipa.callgraph.impl.FakeRootMethod cannot be cast to com.ibm.wala.classLoader.ShrikeBTMethod
```
`
Here is my build code:
```java
public static void sliceFromReturn(String jar,String callname, String callmethodClass) throws IOException, ClassHierarchyException, IllegalArgumentException, InvalidClassFileException, CancelException {
	File exFile=new FileProvider().getFile("Java60RegressionExclusions.txt");
	AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope(jar, exFile);
	ClassHierarchy cha = ClassHierarchyFactory.make(scope);
	Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
	AnalysisOptions options = new AnalysisOptions(scope, entrypoints);
	options.setReflectionOptions(ReflectionOptions.NONE); 
	CallGraphBuilder<InstanceKey> builder = Util.makeZeroCFABuilder(Language.JAVA, options, new AnalysisCacheImpl(), cha, scope);		
	System.out.println("building call graph...");
	CallGraph cg = builder.makeCallGraph(options, null);
        System.out.println("done");
        System.out.println(CallGraphStats.getStats(cg));     	
	final PointerAnalysis<InstanceKey> pa = builder.getPointerAnalysis();
	ModRef<InstanceKey> modRef = ModRef.make(); 		
	SDG<?> sdg = new SDG<>(cg, pa, modRef, DataDependenceOptions.NO_HEAP, ControlDependenceOptions.NO_EXCEPTIONAL_EDGES, null);		
	CGNode nc = null;
	Collection<Statement> collection = null;	
	CGNode n = FindMethod.findMethod(cg, callname, callmethodClass);
	Statement statement = FindStatement.findReturn(n);		
	System.out.println("-------computeBackwardSlice-------");
	collection = Slicer.computeBackwardSlice(sdg, statement);		
	dumpSlice(collection, callname);		
	}
```

And here is my method that catches the return statement:
```java
public static Statement findReturn(CGNode n) {
	IR ir = n.getIR();
        for (Iterator<SSAInstruction> it = ir.iterateAllInstructions(); it.hasNext();) {
		SSAInstruction s = it.next();
		if (s instanceof SSAReturnInstruction) {
			SSAReturnInstruction call = (SSAReturnInstruction) s;
			return new NormalStatement(n, ((SSAReturnInstruction) s).iindex);
		}
	}
	return null;
}
```

**Comment by msridhar** [comment]
@zhangxii I'm not exactly sure why you're not seeing the expected statements in the slice.  Can you post a minimal, complete source code example where when you analyze it you see the problem?

The `FakeRootMethod` is a synthetic method that models calls into the program entrypoints.  Here, since you use `AllApplicationEntrypoints`, WALA creates a synthetic method that invokes `getContentType` with some arbitrary `String`.  Since the method does not come from bytecode it is not an instance of `ShrikeBTMethod`.

**Comment by zhangxii** [comment]
Sorry, I didn't understand the meaning of 'the method does not come from bytecode'. Actually, my example is compiled into a jar before being sliced.

And this is an example of a problem I had:
![image](https://user-images.githubusercontent.com/39162319/64139372-3509cf00-ce33-11e9-9835-26b83a0fcb05.png)

Its console output is:
```
=====  callname: getContentType === callmethodClass: Lexam/GetContentType  ======
building call graph...
done
Call graph stats:
  Nodes: 1047
  Edges: 2135
  Methods: 1047
  Bytecode Bytes: 53728

-------computeBackwardSlice-------
NORMAL getContentType:return 11 Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
NORMAL fakeRootMethod:51 = new <Application,Ljava/lang/String>@46 Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere
NORMAL fakeRootMethod:53 = invokestatic < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > 51 @48 exception:54 Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere
Source line number = 20
it's probably not a BT method (e.g. it's a fakeroot method)
com.ibm.wala.ipa.callgraph.impl.FakeRootMethod cannot be cast to com.ibm.wala.classLoader.ShrikeBTMethod
it's probably not a BT method (e.g. it's a fakeroot method)
com.ibm.wala.ipa.callgraph.impl.FakeRootMethod cannot be cast to com.ibm.wala.classLoader.ShrikeBTMethod
```
The console output only returns the line 20. But I think the line16, 17, 19 should also be returned.

**Comment by msridhar** [comment]
> Sorry, I didn't understand the meaning of 'the method does not come from bytecode'. Actually, my example is compiled into a jar before being sliced.

The fake root method does not represent any real method in your code.  It is a "fake" method created by WALA to model some behaviors not present in the code, e.g., calls to static initializers or an actual call to the `main` method.

Regarding your example, I think I figured out what is going on.  In `Java60RegressionExclusions.txt`, all classes in the `sun.*` packages are excluded.  But many relevant networking classes are in those packages.  I think due to the exclusion, `url1.openConnection()` is not seen as returning any object, and so no call targets are found for `urlc1.getContentType()`.  Since the slicer cannot analyze any implementation of `getContentType()` it does not find the relevant lines in the slice.  I suggest not using `Java60RegressionExclusions.txt`, but using your own custom exclusions file as needed.

**Comment by zhangxii** [comment]
@msridhar 
Thanks for your explanation!  I cleaned the content of the `Java60RegressionExclusions.txt` ,but it doesn't work well. 
As you can see, The call graph is bigger than before, but the slice result is still only one line.
```
=====  callname: getContentType === callmethodClass: Lexam/GetContentType  ======
building call graph...
done
Call graph stats:
  Nodes: 8221
  Edges: 29876
  Methods: 8158
  Bytecode Bytes: 557545

-------computeBackwardSlice-------
NORMAL getContentType:return 11 Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
NORMAL fakeRootMethod:65 = new <Application,Ljava/lang/String>@57 Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere
NORMAL fakeRootMethod:67 = invokestatic < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > 65 @59 exception:68 Node: synthetic < Primordial, Lcom/ibm/wala/FakeRootClass, fakeRootMethod()V > Context: Everywhere
Source line number = 20
it's probably not a BT method (e.g. it's a fakeroot method)
com.ibm.wala.ipa.callgraph.impl.FakeRootMethod cannot be cast to com.ibm.wala.classLoader.ShrikeBTMethod
it's probably not a BT method (e.g. it's a fakeroot method)
com.ibm.wala.ipa.callgraph.impl.FakeRootMethod cannot be cast to com.ibm.wala.classLoader.ShrikeBTMethod
```

**Comment by msridhar** [comment]
Can you print the call graph and see if the `urlc1.getContentType()` call has any targets?

**Comment by zhangxii** [comment]
Yes, as you have guessed , there is no such `urlc1.getContentType()` and `urlc1.getContentLength()` calls in the call graph.

All about node `exam.getContentType` in the call graph as following:
```
Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
 - invokespecial < Application, Ljava/net/URL, <init>(Ljava/lang/String;)V >@7
     -> Node: < Primordial, Ljava/net/URL, <init>(Ljava/lang/String;)V > Context: Everywhere
 - invokevirtual < Application, Ljava/net/URL, openConnection()Ljava/net/URLConnection; >@14
     -> Node: < Primordial, Ljava/net/URL, openConnection()Ljava/net/URLConnection; > Context: Everywhere
```

But when I also printed the SDG, I can find the  `getContentType()` and `getContentLength()`methods.
```
…
NORMAL_RET_CALLER:Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere[8]7 = invokevirtual < Application, Ljava/net/URL, openConnection()Ljava/net/URLConnection; > 4 @14 exception:6
 --> NORMAL getContentType:9 = invokevirtual < Application, Ljava/net/URLConnection, getContentLength()I > 7 @19 exception:8 Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
 --> PARAM_CALLER:Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere[11]9 = invokevirtual < Application, Ljava/net/URLConnection, getContentLength()I > 7 @19 exception:8 v7
 --> NORMAL getContentType:11 = invokevirtual < Application, Ljava/net/URLConnection, getContentType()Ljava/lang/String; > 7 @24 exception:10 Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
 --> PARAM_CALLER:Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere[14]11 = invokevirtual < Application, Ljava/net/URLConnection, getContentType()Ljava/lang/String; > 7 @24 exception:10 v7
…
NORMAL getContentType:9 = invokevirtual < Application, Ljava/net/URLConnection, getContentLength()I > 7 @19 exception:8 Node: < Application, Lexam/GetContentType, getContentType(Ljava/lang/String;)Ljava/lang/String; > Context: Everywhere
…
```
What is causing this problem and how does one resolve it?

**Comment by msridhar** [comment]
I think in the SDG you are only seeing caller nodes, from the call site.  If the call had a target in the call graph, you would see nodes like `PARAM_CALLEE` for the callee method.

Can you paste your updated exclusions here?  I don't have much time to look into this deeply, but what you need to do is figure out what actual methods you expect to be executing when you run this code, and then go step by step through the code to figure out the first thing that WALA misses.  Glancing at the URL [source code](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/net/URL.java), my guess is WALA does not find an object for the `handler` field, maybe because of some native code.  So maybe we need a model somewhere.  But it will take some digging through the call graph and source code to figure out what is going on.

**Comment by zhangxii** [comment]
My exclusions is an empty file now, which I deleted all previous contents. 

When I saw the call graph, I knew there must be something wrong before the call graph was generated. Thank you for your suggestion, I'm trying to read the precedingcode to figure out where the problem is, but I haven't found it yet.

**Comment by zhangxii** [comment]
I made a further discovery, I see four method calls in the `getContentType(String)` method in the return value of the `iterateCallSites()` method of the variable `n`. 
![image](https://user-images.githubusercontent.com/39162319/64472876-974a3300-d197-11e9-8b40-126cf307aa41.png)

Sorry to ask again, but since there is method information in variable `n`, why can't subsequent results be returned?

**Comment by msridhar** [comment]
think what you are seeing are the call *sites*. Those correspond to the call instructions in the program. For the special call, that is a call to a constructor for `URL`. You should see a target for that call in the call graph. Otherwise something strange is going on. The other calls are virtual calls, and the targets get discovered via pointer analysis. If the pointer analysis can’t find any objects that the receiver argument may point to, it won’t find any targets for the call.

**Comment by zhangxii** [comment]
I checked the previous intermediate variables, though I didn't see any new clues. But I've made some new discoveries, and for the following example, something amazing happens. That is the slicing result for this example contains `urlc1.getContentLength()` and `urlc1.getContentType()`.
```
public static String getConTypeTest(String url,URLConnection urlc1) throws MalformedURLException {
		      int i1;
		      String s1 = null;
		      URL url1;
		        url1 = new URL(url);
		        i1 = urlc1.getContentLength();
		        s1 = urlc1.getContentType();
		      return s1;
		  }
```

I analyzed this example and found that if the URLConnection type appears as a parameter, then I can see `urlc1.getContentLength()` and `urlc1.getContentType()` contained in the call graph. But if `urlc1` is reassigned by `openConnection` method, the result goes back over its original form.

The problem now seems to be that `url1.openConnection()` can appear separately in the call graph, as can `urlc1.getContentLength()` and `urlc1.getContentType()`. But if they are all in the code at the same time, all that's left in the call graph is only `url1.openConnection()`.

**Comment by msridhar** [comment]
> I analyzed this example and found that if the URLConnection type appears as a parameter, then I can see `urlc1.getContentLength()` and `urlc1.getContentType()` contained in the call graph. But if `urlc1` is reassigned by `openConnection` method, the result goes back over its original form.

What do you mean that you can see `urlc1.getContentLength()` in the call graph?  Do you mean that when you print the call graph, you see a target callee method for that call site?  If so, what is the callee method?  And what value do you pass in for `URLConnection`?

By the way, an alternate solution for this issue might be to use a [`CHACallGraph`](https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/com/ibm/wala/ipa/callgraph/cha/CHACallGraph.java) rather than using `Util.makeZeroCFABuilder()` to build a call graph.  It will be quite imprecise but it should contain any possible target for these calls that is present in the analysis scope.

**Comment by msridhar** [comment]
I think this version works because you are using
`AllApplicationEntrypoints`. That creates a fake call site for `getConType`
that passes in some arbitrary subtype of `URLConnection` as a parameter.
When you need to get that `URLConnection` from a URL object that’s where
the pointer analysis can’t find an implementation.

**Comment by zhangxii** [comment]
As you said, moving `URLConnection` type into arguments doesn't seem like a good solution.

**Comment by msridhar** [comment]
@zhangxii I am going to close, but if you have further questions here please let us kno.w
