### ISSUE TITLE
AstJavaSlicer.computeSlice can't stop 

### ISSUE THREAD

**Issue by ZhangYiGang** [wala/WALA#622]
Hey,guys.When I'm doing forward slicing, one of the parameters of a function can't be stopped,The program will block in AstJavaSlicer.computeSlice() function without ending or throwing an exception，The parameters I pass are SDG, the type of things to be sliced is paramecallee, false.I've tried the following to prove this, but I don't know why the program stops here
1.  I changed the position of the parameter, but when I sliced the parameter, I couldn't slice it successfully
2. Delete the parameters related to the function (two parameters are used in the same statement), or it will block. Make sure it is not the reason for using other parameters
3. I used source code analysis and bytecode analysis both
4. change the type of the parameter

It's all useless

**Now I paste the program code that can't be sliced**
`   public String readerRePasswdDo(String newPasswd,HttpServletRequest request,String oldPasswd,String reNewPasswd,RedirectAttributes redirectAttributes) {
        ReaderCard readerCard = (ReaderCard) request.getSession().getAttribute("readercard");
        int readerId = readerCard.getReaderId();
        String passwd = readerCard.getPasswd();
        boolean succ = readerCardService.updatePasswd(readerId, oldPasswd);
        if (newPasswd == "123") {
            System.out.print(1);
        }
        return passwd;
    }`
The logic of the program may be a bit wrong (it has been modified many times), but from the point of view of code execution, there is no problem. The first parameter in this code will block when it is de sliced for analysis. When I delete the first parameter and the code related to it, the program can get the slice again. Why？
Hope to get your help.

**Comment by msridhar** [comment]
Slicing Java programs is very difficult to scale.  I suspect you are running into a fundamental scalability problem.  You can potentially fix by decreasing the types of control and data dependencies considered.  See [this mailing list thread](https://groups.google.com/d/msg/wala-sourceforge-net/rbVE1xFaSHs/SXzcwmcRlsUJ).  See also [this discussion](http://wala.sourceforge.net/wiki/index.php/UserGuide:PointerAnalysis#Improving_Scalability) on scaling pointer analysis and slide 73 of the [WALA tutorial](http://wala.sourceforge.net/files/PLDI_WALA_Tutorial.pdf).  I apologize that this documentation is not better organized.

I will close but if you think there's a real bug here please comment

**Comment by shaghayegh70** [comment]
@ZhangYiGang  Hi. I'm not a java developer and I don't know how can I slice the program with wala?
Could you help me? do you have an Instructions or tutorial?

**Comment by ZhangYiGang** [comment]
> @ZhangYiGang Hi. I'm not a java developer and I don't know how can I slice the program with wala?
> Could you help me? do you have an Instructions or tutorial?
Most test cases can be found in com.ibm.wala.core.tests，It contains all the basic slicers.But slice analysis is very difficult for beginners, especially you don't know Java very well

**Comment by ZhangYiGang** [comment]
@shaghayegh70 

Most test cases can be found in com.ibm.wala.core.tests，It contains all the basic slicers.But slice analysis is very difficult for beginners, especially you don't know Java very well

**Comment by shaghayegh70** [comment]
@ZhangYiGang Thank you for your response
