### ISSUE TITLE
Reconcile non-test code in `com.ibm.wala.cast.java.test` and `com.ibm.wala.cast.java` subprojects

### ISSUE THREAD

**Issue by liblit** [wala/WALA#639]
As part of #636, we would like to merge the `com.ibm.wala.cast.java.test` subproject into a new `test` `sourceSet` within the `com.ibm.wala.cast.java` subproject . However, the code in `com.ibm.wala.cast.java.test` is currently part of that subproject’s `main` `sourceSet`. If these two subprojects were merged, either their code would all live in a single `main` `sourceSet` or else code from `com.ibm.wala.cast.java.test` would have to go back to being `test` code rather than `main` code.

Treating `com.ibm.wala.cast.java.test`  code as `main` code rather than `test` code is intentional. @msridhar made that change in 4ed0970896ffab8ebff8186095e302c8960d3b43 to address #612. Whatever we do with this code next should pay heed to that earlier issue and avoid regression.

**Comment by msridhar** [comment]
I remember this one now.  The "right" solution would again be to have the code in `com.ibm.wala.cast.java.test` become a test fixture inside `com.ibm.wala.cast.java`.  The tricky thing is that `com.ibm.wala.ide.jdt.test`, which is still built with Maven, depends on `wala.cast.java.test` as an artifact.  So, this would have to be changed so that `wala.cast.java.test` depends on a new test fixture artifact instead.  I'm not sure how that would be named, but hopefully it wouldn't be too hard to figure out.

This should all eventually work I think.  However, since we still depend on the Gradle `maven` plugin for artifacts rather than `maven-publish`, we may run into some kinks.  It would be nice to switch over to `maven-publish` anyway (see https://github.com/vanniktech/gradle-maven-publish-plugin/issues/75), but maybe that change should be out of scope here if we can get by with something simpler.

**Comment by liblit** [comment]
If approached as @msridhar [recommends](#issuecomment-570087035), then this is a duplicate of #613.
