### ISSUE TITLE
make maven builds reproducible

### ISSUE THREAD

**Issue by mohrm** [wala/WALA#77]
Doing a mvn clean should delete all files which have been downloaded or created during other maven builds. This would enable reproducible builds and uncover nasty errors which only occur if these files are not present.

**Comment by msridhar** [comment]
Agreed that ideally we should have something like this.  Since it takes quite a while to download some of the third-party dependencies, I'm not sure that the `clean` target should delete all those things.  Maybe we should add a different target for this?  I'm not a maven expert, so not sure how this is typically done.  

As an alternative, one thing I do is simply do a fresh clone from a local bare repository and run the maven build and tests on that clone.  Create the bare repository using [these instructions](http://stackoverflow.com/a/7632497/1126796).  Assuming the bare repo is in path `/path/p.git`, in your local WALA repository, push your local changes to the bare repo:

    git remote add local /path/p.git
    git push local cur_branch

Then in a temp directory, get a fresh clone:  

    git clone /path/p.git

And then run the maven builds / tests in the fresh clone.  This whole process avoids having to push to a remote server to do this testing.

**Comment by mohrm** [comment]
Okay, this is a workaround :)
Sure, it does not need to be mvn clean which deletes all these files. However, I still think it would be good if this could be integrated into the maven lifecycle somehow.
