### ISSUE TITLE
Testing PDFSlice with external jar files

### ISSUE THREAD

**Issue by dareenkf** [wala/WALA#829]
When I run "PDFSlice.launch" with the provided example "com.ibm.wala.core.testdata_1.0.0.jar", it works fine. However, when I change the arguments (-appJar, -mainClass, and -srcCallee) to test a new example the launcher doesn't work. 
I got this message "Variable references non-existent resource : ${resource_loc:/Users/X/calculator/add.jar}".  
Do I have to change other settings to test external jar files?

**Comment by msridhar** [comment]
Hi @dareenkf I have not used Eclipse in quite a while so I'm not too sure about this launcher problem unfortunately.  My only suggestion is that rather than using the launcher, use an approach like [WALA-start](https://github.com/wala/WALA-start) where you pull in the WALA jars using Gradle dependencies.  Then you could copy the source code of `PDFSlice` to your own Gradle project and just run the main method using whatever means you normally do.  Sorry to not be more helpful.  I'll leave this issue open in case someone else knows a solution.

**Comment by msridhar** [comment]
Closing out some older issues with no follow-up in a while, but please re-open if there is still an issue
