### ISSUE TITLE
Some questions about transferring statement to bytes.

### ISSUE THREAD

**Issue by wendaojidian** [wala/WALA#854]
Hello,
Recently, I'm learning how to use wala to do the slicing work. Here comes my questions:

1. I got stuck in transferring a list of statements sliced by a seed to the bytecodes, and then write them to a class file. I've read the "PLDI_WALA_Tutorial" and have known that it can be accomplished with shrike. But how can I construct the ShrikeBT method with the statement and wirte them into a class file?
![1](https://user-images.githubusercontent.com/48314235/103744269-74a08680-5038-11eb-8b02-966944ea6c19.png)
![2](https://user-images.githubusercontent.com/48314235/103744277-766a4a00-5038-11eb-9131-63cc592add39.png)

2.I don't understand how to use the Inner static abstract class MethodEditor.Patch. What's the relationship between it and the bytecode?
![3](https://user-images.githubusercontent.com/48314235/103744710-322b7980-5039-11eb-98b5-6defab27eaad.png)
![4](https://user-images.githubusercontent.com/48314235/103744720-35266a00-5039-11eb-8265-685ff0bb55d3.png)

3.If I get the bytecodestream from the ShrikeBTMethod, how can I read the bytecodes from the stream?
![image](https://user-images.githubusercontent.com/48314235/103744910-86365e00-5039-11eb-9164-66693cd38e4a.png)

Hope for your answers, I would thanks a lot.

**Comment by msridhar** [comment]
@wendaojidian very sorry for the slow response.  First, I'd like to clarify that the slices computed by WALA are _closure_ slices, which may not be _executable_ slices.  See this paper for a discuss of the difference:

https://research.cs.wisc.edu/wpis/papers/tr1711.pdf

Regarding your proposed usage of Shrike, I think what you'd like to do is take the original bytecodes and delete those that are not in the slice, correct?  There are some instructions on mapping IR instructions back to source code and byte code indices here:

https://github.com/wala/WALA/wiki/Mapping-to-source-code

But in general, I think this might be a tricky process, both because you need an executable slice, and because I'm not fully confident that all the info you need is preserved in the WALA IR.

If you make further progress on creating executable slices from WALA slices, please let us know; I think it would be of interest to the community.  And sorry again for my slow response; let us know if you have further questions.

**Comment by msridhar** [comment]
closing but if there are more questions let us know
