### ISSUE TITLE
wala-ide.jar 

### ISSUE THREAD

**Issue by Playwi0** [wala/WALA#921]
There is not wala-ide.jar in maven repository.
How should I get it ?
Can you upload it to the maven repository?

**Comment by msridhar** [comment]
Hi @Playwi0 what exactly are you trying to do?  Usually when someone wants to use the WALA IDE functionality, it's as part of an Eclipse plug-in, and last I checked Maven Central was not the preferred way to package such things.  You can always clone the WALA repo and run `./gradlew compileJava`, which should build all the jars.  They will be available under the `build` sub-directory of each module.

If you give more details on what you are trying, we can try to help more.

**Comment by Playwi0** [comment]
```java
ContextSensitiveReachingDefs reachingDefs = new ContextSensitiveReachingDefs(cg);

TabulationResult<BasicBlockInContext<IExplodedBasicBlock>, CGNode, Pair<CGNode, Integer>> result = reachingDefs.analyze();

Collection<BasicBlockInContext<IExplodedBasicBlock>> supergraphNodesReached = result.getSupergraphNodesReached();

for (BasicBlockInContext<IExplodedBasicBlock> blockInContext: supergraphNodesReached){

  System.out.println(blockInContext);

  IntSet intSet = result.getResult(blockInContext);

  System.out.println(intSet);
}
```
![image](https://user-images.githubusercontent.com/43485833/127420669-a5e66d2d-e446-4590-9b54-dce9062b5ea6.png)

When I try to print out some analysis results,I don’t understand the meaning of these `inset`. Therefore,  I try to use `com.ibm.wala.ide.ui.IFDSExplorer.viewIFDS(result);` 

what is meaning of these `inset` or how to use the result?
Can you give me some suggestions?

**Comment by msridhar** [comment]
This is a great question!  Sorry this is not documented more clearly.  Those integers are keys in a domain map, where the values are the actual data flow facts.  To get the mapping, do `reachingDefs.getDomain()`, and to look up an integer in the map, call `getMappedObject(int)` on the returned object, e.g.:
```java
Pair<CGNode, Integer> fact = reachingDefs.getDomain().getMappedObject(intVal);
```
The `fact` here is a `Pair` of a `CGNode`, for the call graph node, and an `Integer` for the IR index of the "def" instruction, which in this case must be an `SSAPutInstruction` on a static field.  To get the actual instruction, you can do:
```java
CGNode node = fact.fst;
SSAInstruction instr = node.getIR().getInstructions()[fact.snd];
```
I hope that is helpful.

In terms of the `IFDSExplorer`, last I checked that had to be run from within some kind of Eclipse plug-in, but I will look again and get back to you.  It's basically a visualizer that shows the control-flow graph, instructions, and reaching facts in a graphical view.

**Comment by Playwi0** [comment]
Thank you very much for your help!
Unfortunately,I tried many methods and still can't run `IFDSExplorer`.
![image](https://user-images.githubusercontent.com/43485833/127794655-5bbf34ba-b2c7-45ac-8e82-ce8ff6c71873.png)
![image](https://user-images.githubusercontent.com/43485833/127794727-413adfb1-aaef-4460-8770-9d75e8aba897.png)
How can I run `IFDSExplorer`.

**Comment by msridhar** [comment]
Sorry it’ll take me a bit of some to look into this. I’ll report back when
I know more.

**Comment by msridhar** [comment]
@Playwi0 as you can see we did some work to revive the `IFDSExplorerExample` code now included in WALA.  If you clone the latest WALA master branch, you should be able to run `./gradlew :com.ibm.wala.ide.tests:runIFDSExplorerExample` and see it working.  You need to provide paths to your dot executable and PDF viewer, see the example:

https://github.com/wala/WALA/blob/e9aded8602b0dfb7efc5ad9cf0242fc59bd8d710/com.ibm.wala.ide.tests/build.gradle#L65-L67

Unfortunately, packaging up the code into a Maven artifact that "just works" will be hard, because it relies on platform-specific GUI libraries.  The right library gets pulled in automatically when you build from source, but I don't think we can upload a Maven artifact that will automatically pull down the right library.  So, for now, you'll need to build WALA from source code to use `IFDSExplorer`.

Can you try and see if it works for you?

**Comment by Playwi0** [comment]
Thank you very much, I successfully executed it on mac, which is very helpful.
