### ISSUE TITLE
Is there a more efficient way to get the CGNode's predNode?

### ISSUE THREAD

**Issue by Anditty** [wala/WALA#924]
The implementation of callgraph I am using is CHAcallgraph, when I want to get the predNodes of a CGNode, the implementation of CHACallgraph iterates through all the nodes to find the eligible CGNode, I would like to know if there is a more efficient way to implement in wala?

**Comment by msridhar** [comment]
Good question! Fundamentally, finding all callers of a method requires going through all code to find all possible call sites. Is the information cached at least? If not, you could try to add that. Also you could imagine techniques to avoid inspecting some code in some cases (e.g. to find callers of a non-public method).

**Comment by Anditty** [comment]
I found that some callgraphs are very fast at handling this, for example ExplicitCallGraph is much faster than CHACallGraph, but it seems that for ExplicitCallGraph if there is a class that is not in the scope file, then the method that uses the instance of that class as the parameter will not be added to the callgraph, but CHACallGraph does not have this problem.  This is very difficult for me and I would like to know if there is a better solution?

**Comment by Anditty** [comment]
Does that mean that if I want to use ExplicitCallGraph, I have to put in all the dependent classes for analysis? I want to just put in some of the classes for analysis like CHACallGraph, but I don't want to lose any of the methods of the classes I'm analyzing, is this possible?

**Comment by msridhar** [comment]
Call graph builders other than CHACallGraph do some reasoning about code reachability starting from entry points.  I think the shortcoming in `ExplicitCallGraph` that you are pointing out is due to this issue, though I'm not 100% sure (a code example would be helpful).  Basically, if the call graph builder does not see a call to some method from some other reachable method, then it will not be included in the call graph.  Is this the issue you are referring to?

In any case, I think what you want is the `CHACallGraph`.  Do you see a high cost every time you ask for node predecessors, or just the first time?  Another possibility here is to use an exclusions file when constructing the `AnalysisScope` to excluded a bunch of code from the class hierarchy entirely.  Here is an example of one:

https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/main/resources/Java60RegressionExclusions.txt

You pass in the location of the exclusions file when constructing the `AnalysisScope`.

**Comment by msridhar** [comment]
@Anditty I'm going to assume this is resolved for you; if not, please re-open.

**Comment by Anditty** [comment]
In fact, I took a look at wala's implementation of chacallgraph and he traverses the entire callgraph for each prevNode node, which is undoubtedly a huge overhead, and I suggest that you maintain a pointer to save such time overhead. Anyway, thank you very much for your suggestion! Thanks!

**Comment by msridhar** [comment]
> In fact, I took a look at wala's implementation of chacallgraph and he traverses the entire callgraph for each prevNode node, which is undoubtedly a huge overhead, and I suggest that you maintain a pointer to save such time overhead. Anyway, thank you very much for your suggestion! Thanks!

By "pointer" do you mean a cache?  If so, sounds like a good suggestion to me.  We'd welcome a PR adding that!

**Comment by Anditty** [comment]
Yes, that's what I mean. When I'm free, I'm very willing to make a contribution to wala.
