### ISSUE TITLE
Support for ES6 

### ISSUE THREAD

**Issue by niklbird** [wala/WALA#927]
Is there an easy way to build a WALA callgraph with the language settings for ES6? 
Im using the CAstRhinoTranslatorFactory to build the callgraph. 
Implementing support for ES6 should be straightforward as Rhino already supports it, but I was wondering if there is already an option for ES6 which I did not find.
Cheers!

**Comment by msridhar** [comment]
Hi @niklbird, unfortunately ES6 support is not all that straightforward, since all the ES6 constructs need to be translated to WALA IR after getting parsed by Rhino.  There is a WIP pull request on adding support for arrow functions in https://github.com/wala/WALA/pull/830; I've been too busy to get back to reviewing that.  But there will definitely be other significant work required beyond that to fully handle ES6, e.g., support for classes.

Are there particular ES6 features that are important to you?

**Comment by niklbird** [comment]
Hi @msridhar thank you for your reply. 
I was refering to the "let" keyword as this caused problems in my code. I changed the language setting of Rhino in my local code and it now works as a charme.
In the long term it would of course be awesome if classes would also be supported, but I see how this requires major effort!
Thank you for your help!
